package com.rs.network.codec.update;

public enum JS5State {
	FILE_REQUEST_LOW_PRIORITY,
	FILE_REQUEST_HIGH_PRIORITY,
	FILE_REQUEST_ONLINE,
	FILE_REQUEST_IDLE,
	FILE_REQUEST_XOR,
	FILE_REQUEST_EMPTY,
	FILE_REQUEST_STARTUP,
	FILE_REQUEST_COMPLETE,

	STATE_SELECTOR
}