package com.rs.game.player.content.petperks;

import com.rs.game.player.content.pet.Pets;

import static com.rs.game.player.content.pet.Pets.*;

/**
 * ataraxia-server
 * paolo 09/07/2019
 * #Shnek6969
 */
public class PetPerkConstants {


    public static Pets[] FollowerPets = {
            PIGGLES,
            ENTLING,
            CHEERLEADER,
            TINY_LUCIEN,
            KIPPLE_NANO,
            TINY_HAZEEL,
            SAYLN_THE_SHARK,
            TIM,
            CRUNCHY,
            IDOL_CRABLETINE,
            TINY_KHARSHAI,
            TINY_SLISKE,
            STRINGY,
            SHADOW_GORILLA,
            JUNGLE_GORILLA,
            PET_OF_SPRING,
            PET_OF_SUMMER,
            PET_OF_AUTUMN,
            PET_OF_WINTER,
            GOLDEN_CHINCHOMPA,
            FIMBERZIZZ,
            VORAGO_SHARD,
            DAWN,
            DUSK,
            ELVIS_PRESSIE,
            DRAKEFIRE_WARSHIP,
            INARI,
            BRIGHTFLAME_ANCIENT,
            ZENN,
            DOUGLAS,
            FIRE_LYCAN,
            ISHARA,
            SPRINGY,
            RUNEFEST_DRAG,
            ROWENA,
            POSTIE_PETE,
            JAGUAR_CUB,
            TIGER_CUB,
            LION_CUB,
            SNOW_LEOPARD_CUB,
            SEARING_FLAME,
            GLOWING_EMBER,
            TWISTED_FIRESTARTER,
            WARMING_FLAME,
            SPARKLES,
            MACKERS,
            TINY_DEATH,
            TROLL_BABY,
            FROSTY,
            MINI_BLINK,
            HOPE_NIBBLER,
            BULLDOG,
            DALMATIAN,
            GREYHOUND,
            LABRADOR,
            SHEEPDOG,
            TERRIER,
            CREEPING_HAND,
            MINITRICE,
            BABY_BASILISK,
            BABY_KURASK,
            ABYSSAL_MINION,
            RUNE_GUARDIAN,
            GECKO,
            GECKO_1,
            GECKO_2,
            GECKO_3,
            GECKO_4,
            PLATYPUS,
            BROAV,
            PENGUIN,
            TOOTH_CREATURE,
            GIANT_CRAB,
            RAVEN,
            SQUIRREL,
            SARADOMIN_OWL,
            ZAMORAK_HAWK,
            GUTHIX_RAPTOR,
            EX_EX_PARROT,
            CUTE_PHOENIX_EGGLING,
            RACCOON,
            SNEAKER_PEEPER,
            VULTURE,
            CHAMELEON,
            MONKEY,
            BABY_DRAGON,
            BABY_DRAGON_1,
            BABY_DRAGON_2,
            BABY_DRAGON_3,
            SCURVY,
            SQUIDGE,
            FREEZY_ICE,
            FREEZY_SAND,
            FREEZY_JUNGLE,
            FREEZY_LAVA,
            RUNTSTABLE,
            LIL_GOOP,
            CRESBOT,
            CORGI,
            EFFY
    };

    public static Pets[] SkillingPets = {
            AGILITY,
            CONSTRUCTION,
            COOKING,
            CRAFTING,
            DIVINATION,
            DUNGEONEERING,
            FARMING,
            FIREMAKING,
            FISHING,
            FLETCHING,
            HERBLORE,
            HUNTER,
            INVENTION,
            MINING,
            RUNECRAFTING,
            SLAYER,
            SMITHING,
            THIEVING,
            WOODCUTTING
    };

    public static Pets[] LegendaryPets = {
            BLAZEHOUND,
            SKYPOUNCER,
            BLOODPOUNCER,
            DRAGON_WOLF,
            WARBORN_BEHEMOTH,
            PROTOTYPE_COLOSSUS,
            RORY_THE_REINDEER,
            SHADOW_DRAKE,
            FIRE_DRAKE,
            SANTAR_SPAWNLING
    };

    public static Pets[] TreasureHunterPets = {
            TUMBLEWEED,
            SQIRKS,
            SKULLY,
            HYPE_TRAIN,
            PUMPKINCROW,
            HELPS,
            KHARIDIAN_CAT,
            MIMIC,
            BUDDY,
            ARMADYL_BANNER,
            GODLESS_BANNER,
            SARADOMIN_BANNER,
            ZAMORAK_BANNER,
            PIRATE_SHEEP,
    };

    public static Pets[] CombatPets = {
            CONSTITUTION,
            ATTACK,
            STRENGTH,
            DEFENCE,
            RANGED,
            PRAYER,
            MAGIC,
            SUMMONING,
    };

    public static Pets[] BossPets = {
            DAVE,
            STEVE,
            PETE,
            GAVIN,
            LANA,
            BILL,
            DAG_PRIME,
            DAG_SUPREME,
            DAG_REX,
            CHAOS_ELLIE,
            CORP_BEAST,
            KBD,
            NEX,
            BANDOS,
            ZAMMY,
            SARA,
            ARMA,
            BARRY,
            MALLORY,
            MOLLY,
            SHRIMPY,
            KALPHITE_KING,
            QBD,
            VITALIS,
            BOMBI,
            LEGIO_PRIMUS,
            LEGIO_SECUNDUS,
            LEGIO_TERTIUS,
            LEGIO_QUARTUS,
            LEGIO_QUINTUS,
            LEGIO_SEXTUS,
            KALPHITE_GRUBLET_I,
            KALPHITE_GRUBLET_II,
            ENDURING_GLACYTE,
            SAPPING_GLACYTE,
            UNSTABLE_GLACYTE,
            EDDY,
            ENTLING,
            TESS,
            VINDIDDY,
            RAWRVEK,
            LILWYR,
            GREG,
            NYLESSA,
            AVA,
            AHRIM,
            DHAROK,
            GUTHAN,
            KARIL,
            TORAG,
            VERAC,
            TUZZY,
            KRARJNR,
            YAKAMINU,
            REEVES,
            THE_MINISTER,
            TZREK_JAD, 
            KURORYU


    };
}
