package com.rs.game.player.client;
import com.rs.cache.Cache;import com.rs.cache.loaders.*;import com.rs.cache.loaders.rs3.RS3GeneralRequirementMap;import com.rs.game.WorldObject;import com.rs.game.item.Item;import com.rs.game.player.Player;import com.rs.game.player.Skills;import com.rs.game.player.content.construction.HouseConstants.HObject;import java.util.*;
/** Original HouseConstants furniture policy with current950 materials, level and flatpack output. */
public final class Native950Construction {
 private Native950Construction(){}private static Object store;private static List<Native950Production.Recipe> cached;
 public static synchronized List<Native950Production.Recipe> recipes(){if(Cache.STORE==null||!Cache.isFlatReadOnly())return Collections.emptyList();if(store==Cache.STORE&&cached!=null)return cached;store=Cache.STORE;List<Native950Production.Recipe> list=new ArrayList<>();
  for(String[] row:Native950FarmingConstructionAssets.rows("construction-furniture-950.tsv")){HObject old=HObject.valueOf(row[0]);int id=Integer.parseInt(row[1]);if(!Native950FarmingConstructionAssets.item(id))continue;ItemDefinitions d=ItemDefinitions.getItemDefinitions(id);int level=d.getCSOpcode(2645,0);if(d.getCSOpcode(2640,0)!=22||level<1||level>120)continue;List<Item> inputs=new ArrayList<>();Map<Integer,int[]> alternatives=new LinkedHashMap<>();boolean valid=true;
   for(int i=0;i<10;i++){int item=d.getCSOpcode(2655+i,0),amount=d.getCSOpcode(2665+i,0);if(item>0){if(amount<1||amount>10000||!Native950FarmingConstructionAssets.item(item)){valid=false;break;}inputs.add(new Item(item,amount));}int struct=d.getCSOpcode(2675+i,0);if(struct>0){if(!Native950FarmingConstructionAssets.pin("struct",struct)){valid=false;break;}RS3GeneralRequirementMap m=RS3GeneralRequirementMap.getMap(struct);Item selected=null;for(Item wanted:old.getRequirements())for(int n=0;n<10;n++)if(m.getIntValue(2655+n)==wanted.getId()&&m.getIntValue(2665+n)>0)selected=new Item(wanted.getId(),m.getIntValue(2665+n));if(selected==null||!Native950FarmingConstructionAssets.item(selected.getId())){valid=false;break;}inputs.add(selected);List<Integer> ids=new ArrayList<>();for(int n=0;n<10;n++){int candidate=m.getIntValue(2655+n);if(m.getIntValue(2665+n)==selected.getAmount()&&Native950FarmingConstructionAssets.item(candidate))ids.add(candidate);}int[] allowed=new int[ids.size()];for(int n=0;n<allowed.length;n++)allowed[n]=ids.get(n);alternatives.put(selected.getId(),allowed);}}
   if(valid&&!inputs.isEmpty()){Native950Production.Recipe recipe=new Native950Production.Recipe("Flatpack: "+d.name,Skills.CONSTRUCTION,level,old.getXP(),3683,3,inputs.toArray(new Item[0]),new Item[]{new Item(id,1)},2347,8794);for(Map.Entry<Integer,int[]> a:alternatives.entrySet())recipe=recipe.withAlternatives(a.getKey(),a.getValue());list.add(recipe);}
  }cached=Collections.unmodifiableList(list);return cached;
 }
 public static boolean isStation(WorldObject o){if(o==null||o.getType()<0||o.getType()>22||!Native950FarmingConstructionAssets.pin("object",o.getId()))return false;ObjectDefinitions d=o.getDefinitions();return d.loaded&&d.transforms==null&&d.sizeX>=1&&d.sizeX<=8&&d.sizeY>=1&&d.sizeY<=8&&((o.getId()>=13704&&o.getId()<=13708)||"Furniture workbench".equals(d.name));}
 public static boolean handles(WorldObject o,int option){if(!isStation(o)||option<1||option>5)return false;String op=o.getDefinitions().options[option-1];return "Construct".equalsIgnoreCase(op)||"Work-at".equalsIgnoreCase(op);}
 public static boolean inReach(Player p,WorldObject o){return p!=null&&isStation(o)&&p.getNextWalkDirection()==-1&&!p.hasTeleported()&&Native950Mining.current(o)&&Native950Mining.inReach(p,o);}
 public static List<Native950ProductionMenu.Choice> choices(Player p,WorldObject o){List<Native950ProductionMenu.Choice> list=new ArrayList<>();if(!inReach(p,o))return list;for(Native950Production.Recipe r:recipes()){boolean primary=false;for(Item i:r.consumed())if(i.getId()!=1539&&p.getInventory().containsItem(i.getId(),1)){primary=true;break;}if(primary)list.add(new Native950ProductionMenu.Choice(r.label.substring(10)+" (level "+r.level+")",r,n->start(p,o,r,n)));}if(list.isEmpty())p.sendMessage("Bring planks, a hammer and a saw to construct flatpack furniture. Basic planks also need nails of any metal grade.");return list;}
 public static boolean start(Player p,WorldObject o,Native950Production.Recipe r,int quantity){if(p==null||r==null||quantity<1||quantity>10000||!recipes().contains(r)||!inReach(p,o))return false;if(r.level>workbenchLimit(o)){p.sendMessage("This workbench only supports flatpacks up to level "+workbenchLimit(o)+". Use a higher-tier furniture workbench.");return false;}p.setNextFaceWorldTile(o);return p.getActionManager().setAction(new Native950ProductionAction(r,quantity){@Override protected boolean environment(Player p){return inReach(p,o);}});}
 public static int workbenchLimit(WorldObject o){if(!isStation(o))return 0;return o.getId()>=13704&&o.getId()<=13708?new int[]{20,40,60,80,99}[o.getId()-13704]:120;}
 public static boolean acceptsItem(WorldObject o,int id){if(!isStation(o))return false;for(Native950Production.Recipe r:recipes()){if(r.usesInput(id))return true;for(int tool:r.tools())if(tool==id)return true;}return false;}
 public static Native950ItemCatalog.Entry itemEntry(int id){return Native950FarmingConstructionAssets.entry(id);}public static List<Native950ItemCatalog.Entry> itemEntries(){return Native950FarmingConstructionAssets.entries();}
 public static void verifyCacheBindings(){Native950FarmingConstructionAssets.verify();if(recipes().size()!=45)throw new IllegalStateException("Expected45 current flatpack recipes, got "+recipes().size());}
}
