package com.rs.game.player.client;
import com.rs.cache.Cache;import com.rs.cache.loaders.ObjectDefinitions;import com.rs.cores.CoresManager;import com.rs.game.*;import com.rs.game.item.Item;import com.rs.game.player.Player;import com.rs.game.player.Skills;import com.rs.network.modern.*;import io.netty.channel.embedded.EmbeddedChannel;import io.netty.util.ReferenceCountUtil;import java.nio.file.Paths;import java.util.*;import java.util.concurrent.TimeUnit;import java.lang.reflect.Constructor;import com.rs.network.io.InputStream;import java.io.ByteArrayOutputStream;
/** Cache-backed recipe/action acceptance, without listener, credentials or character saves. */
public final class Native950FarmingConstructionAcceptance {
 private static int assertions,ticks;
 public static void main(String[] a)throws Exception {System.setProperty(Native950World.SPAWNS_PROPERTY,"false");System.setProperty(Native950World.LEGACY_SPAWNS_PROPERTY,"false");Cache.initFlatReadOnly(Paths.get(a[0]));Native950World.getInstance().execute(()->{Native950Farming.verifyCacheBindings();Native950Construction.verifyCacheBindings();try(Fixture f=new Fixture()){check(f);morphDecoder();}return null;}).get(120,TimeUnit.SECONDS);require(CoresManager.getNative950Scheduler().failed()==0,"Scheduler failed");System.out.println("PASS Farming/Construction: "+Native950Farming.crops().size()+" crops, "+Native950Construction.recipes().size()+" flatpacks, "+ticks+" engine ticks, "+assertions+" checks. No account save or network listener.");}
 static void check(Fixture f){WorldObject allotment=f.station(8550),herb=f.station(8150),flower=f.station(7847),hops=f.station(8173),bench=f.station(139147);Map<Integer,WorldObject> types=new HashMap<>();types.put(0,allotment);types.put(6,herb);types.put(3,flower);types.put(2,hops);f.level(Skills.FARMING,99);f.level(Skills.CONSTRUCTION,99);
  require(Native950Farming.matches(allotment,8576,f.p),"Rake morph not accepted");require(!Native950Farming.matches(allotment,8558,f.p),"Unplanted morph accepted");
  f.clear();f.beside(allotment);f.give(5341,1);require(Native950Farming.rake(f.p,allotment),"Rake failed");f.run(8);require(f.amount(6055)==3,"Weeds missing");require(Native950Farming.snapshot(f.p).get(0).cleared,"Raking did not clear");WorldObject secondTile=f.station(8550);require(Native950Farming.definition(f.p,secondTile).id==8573,"One allotment scenery tile lost shared plot state");
  for(Native950Farming.Crop c:Native950Farming.crops()){f.clear();WorldObject o=types.get(c.type);f.beside(o);Native950Farming.restore(f.p,Arrays.asList(empty(o)));f.give(5325,1);f.give(952,1);f.give(c.seed,c.seeds);double xp=f.p.getSkills().getXp(Skills.FARMING);require(Native950Farming.plant(f.p,o,c.seed),"Plant "+c.seed);f.run(5);require(f.amount(c.seed)==0,"Seeds not consumed "+c.seed);require(f.amount(5325)==1,"Dibber lost");require(f.p.getSkills().getXp(Skills.FARMING)>xp,"Plant XP");Native950Farming.Plot saved=Native950Farming.snapshot(f.p).get(0);require(saved.seedId==c.seed,"Crop not stored");require(Native950Farming.definition(f.p,o)!=null,"Growing definition absent");Native950Farming.restore(f.p,Arrays.asList(new Native950Farming.Plot(o.getId(),o.getX(),o.getY(),o.getPlane(),c.seed,System.currentTimeMillis()-c.growMillis-1000,true,saved.compost,saved.harvestRemaining)));Native950Farming.refresh(f.p);require(Native950Farming.definition(f.p,o).options[0]!=null,"Mature option missing");require(Native950Farming.harvest(f.p,o),"Harvest failed "+c.seed);int harvested=0;for(int batch=0;batch<4;batch++){f.run(100);harvested+=f.amount(c.produce);for(int slot=0;slot<28;slot++){Item held=f.p.getInventory().items.get(slot);if(held!=null&&held.getId()==c.produce)f.p.getInventory().items.set(slot,null);}if(Native950Farming.snapshot(f.p).get(0).seedId==0)break;require(Native950Farming.harvest(f.p,o),"Resume saved harvest "+c.seed);}require(harvested==saved.harvestRemaining,"Harvest must preserve exactly its saved roll "+c.seed);require(Native950Farming.snapshot(f.p).get(0).seedId==0,"Harvest never emptied patch");require(f.amount(952)==1,"Spade lost");}
  // Applying and upgrading compost on a growing crop must preserve its original clock and rolled harvest.
  f.clear();f.beside(allotment);Native950Farming.restore(f.p,Arrays.asList(empty(allotment)));f.give(5325,1);f.give(5318,3);f.give(6032,1);f.give(6034,1);f.give(43966,1);
  require(Native950Farming.plant(f.p,allotment,5318),"Growing compost setup");f.run(5);Native950Farming.Plot growing=Native950Farming.snapshot(f.p).get(0);int previous=growing.harvestRemaining;
  for(int id:new int[]{6032,6034,43966}){double before=f.p.getSkills().getXp(Skills.FARMING);require(Native950Farming.compost(f.p,allotment,id),"Growing compost "+id);f.run(5);Native950Farming.Plot next=Native950Farming.snapshot(f.p).get(0);require(next.plantedAt==growing.plantedAt&&next.seedId==5318,"Compost reset crop clock/type");require(next.harvestRemaining>=previous&&next.harvestRemaining<=60,"Compost did not add bounded harvest lives");previous=next.harvestRemaining;require(f.amount(id)==0&&f.p.getSkills().getXp(Skills.FARMING)>before,"Compost did not atomically consume/reward");}
  require(f.amount(1925)==3,"Compost lost empty buckets");f.give(43966,1);double before=f.p.getSkills().getXp(Skills.FARMING);Native950Farming.Plot treated=Native950Farming.snapshot(f.p).get(0);require(Native950Farming.compost(f.p,allotment,43966),"Repeat compost response");f.run(5);require(f.amount(43966)==1&&Native950Farming.snapshot(f.p).get(0)==treated&&f.p.getSkills().getXp(Skills.FARMING)==before,"Repeat compost duplicated harvest/XP or consumed bucket");
  for(Native950Production.Recipe r:Native950Construction.recipes()){f.clear();f.beside(bench);for(Item i:r.consumed())f.give(i.getId(),i.getAmount());for(int tool:r.tools())f.give(tool,1);double xp=f.p.getSkills().getXp(Skills.CONSTRUCTION);require(Native950Construction.start(f.p,bench,r,1),"Flatpack start "+r.label);f.run(10);require(f.amount(r.produced()[0].getId())==1,"Flatpack output "+r.label);for(Item i:r.consumed())require(f.amount(i.getId())==0,"Material not consumed "+r.label);require(f.amount(2347)==1&&f.amount(8794)==1,"Construction tools consumed");require(f.p.getSkills().getXp(Skills.CONSTRUCTION)>xp,"Construction XP");}
  f.clear();f.beside(allotment);Native950Farming.restore(f.p,Arrays.asList(empty(allotment)));f.give(5325,1);f.give(5318,3);double xp=f.p.getSkills().getXp(Skills.FARMING);require(Native950Farming.plant(f.p,allotment,5318),"Cancellation setup");f.p.getActionManager().forceStop();f.run(8);require(f.amount(5318)==3&&f.p.getSkills().getXp(Skills.FARMING)==xp,"Cancelled planting granted XP/consumed seeds");require(Native950Farming.plant(f.p,allotment,5318),"Distance setup");f.p.setLocation(new WorldTile(allotment.getX()+10,allotment.getY()+10,0));f.run(8);require(f.amount(5318)==3,"Remote planting consumed seeds");
  f.clear();f.beside(allotment);Native950Farming.Crop potato=Native950Farming.crop(5318);Native950Farming.restore(f.p,Arrays.asList(new Native950Farming.Plot(allotment.getId(),allotment.getX(),allotment.getY(),0,5318,System.currentTimeMillis()-potato.growMillis-1000,true,0,7)));f.give(952,1);f.give(960,27);require(Native950Farming.harvest(f.p,allotment),"Full backpack setup");f.run(8);require(Native950Farming.snapshot(f.p).get(0).harvestRemaining==7&&f.amount(1942)==0,"Full backpack lost crop");
 }
 static Native950Farming.Plot empty(WorldObject o){return new Native950Farming.Plot(o.getId(),o.getX(),o.getY(),o.getPlane(),0,0,true,0,0);}
 static void morphDecoder()throws Exception {ObjectDefinitions herb=ObjectDefinitions.getObjectDefinitions(8150);require(herb.configFileId==124&&herb.configId==-1&&herb.transforms.length==257&&herb.transforms[8]==8143,"Current207 herb morph decode");Constructor<ObjectDefinitions> c=ObjectDefinitions.class.getDeclaredConstructor();c.setAccessible(true);ObjectDefinitions d=c.newInstance();ByteArrayOutputStream b=new ByteArrayOutputStream();for(int v:new int[]{1,0,1,255,255,0,7,128,128})b.write(v);for(int i=0;i<=128;i++){b.write(i>>>8);b.write(i);}InputStream in=new InputStream(b.toByteArray());d.readValues(in,208);require(d.configFileId==65537&&d.configId==-1&&d.transforms.length==130&&d.transforms[129]==7&&d.transforms[128]==128&&in.getRemaining()==0,"Wide950208 morph count/fallback");d=c.newInstance();d.readValues(new InputStream(new byte[]{-1,-1,-1,-1,-1,0,0,1}),207);require(d.configFileId==-1&&d.configId==-1&&d.transforms[0]==1&&d.transforms[1]==-1,"950 absent-var sentinels");}
 static final class Fixture implements AutoCloseable {final Native950GameTransport transport=new Native950GameTransport(new Native950Isaac(new int[]{9,5,0,3}),new Native950Isaac(new int[]{59,55,50,53}),Thread.currentThread());final EmbeddedChannel channel=new EmbeddedChannel(transport);final Player p;final List<WorldObject> objects=new ArrayList<>();Fixture(){p=Player.createNative950("farm-construction",new WorldTile(3217,3258,0),channel);p.setActive(true);Native950World.installVarpSink(p);World.addNative950Player(p,1);World.updateEntityRegion(p);p.loadMapRegions();p.setClientHasLoadedMapRegion();Native950Skilling.attach(p,new Native950Containers(p,new Native950ItemCatalog(Native950Construction.itemEntries())));p.resetMasks();drain();}
  WorldObject station(int id){for(int y=3255;y<3290;y++)for(int x=3205;x<3250;x++){WorldObject o=new WorldObject(id,10,0,x,y,0);boolean clear=true;for(int dx=-1;dx<=o.getDefinitions().sizeX;dx++)for(int dy=-1;dy<=o.getDefinitions().sizeY;dy++)if(!World.isFloorFree(0,x+dx,y+dy,1))clear=false;if(!clear)continue;World.spawnObject(o);objects.add(o);beside(o);return o;}throw new AssertionError("No station site "+id);}
  void beside(WorldObject o){p.resetWalkSteps();for(int dx=-1;dx<=o.getDefinitions().sizeX;dx++)for(int dy=-1;dy<=o.getDefinitions().sizeY;dy++){if(!World.isFloorFree(0,o.getX()+dx,o.getY()+dy,1))continue;p.setLocation(new WorldTile(o.getX()+dx,o.getY()+dy,0));World.updateEntityRegion(p);p.resetMasks();if(Native950Mining.current(o)&&Native950Mining.inReach(p,o))return;}throw new AssertionError("No reachable side "+o.getId());}
  void give(int id,int n){require(Native950Skilling.giveItem(p,id,n),"Give "+id+"x"+n);}int amount(int id){return p.getInventory().items.getNumberOf(id);}void level(int skill,int n){p.getSkills().setXpWithoutRefresh(skill,Skills.getXPForLevel(skill,n));p.getSkills().setLevelWithoutRefresh(skill,n);}void clear(){p.getActionManager().forceStop();p.resetWalkSteps();p.resetMasks();for(int i=0;i<28;i++)p.getInventory().items.set(i,null);}void run(int n){for(int i=0;i<n;i++){ticks++;p.processEntity();p.processEntityUpdate();drain();p.resetMasks();}}void drain(){channel.flush();channel.runPendingTasks();Object m;while((m=channel.readOutbound())!=null)ReferenceCountUtil.release(m);channel.checkException();require(transport.terminalFailure()==null,"Transport failed");}public void close(){p.getActionManager().forceStop();for(WorldObject o:objects)World.removeObject(o);Native950Skilling.detach(p);World.removeNative950Player(p);channel.finishAndReleaseAll();}
 }
 static void require(boolean ok,String why){assertions++;if(!ok)throw new AssertionError(why);}
}
