package com.rs.game.player.client;

import com.rs.cache.Cache;
import java.nio.file.Paths;
import java.util.*;

/** Read-only paired-cache catalogue audit; see BankAcceptance for encrypted ownership tests. */
public final class Native950EquipmentLibraryAcceptance {
    public static void main(String[] args)throws Exception{
        Cache.initFlatReadOnly(Paths.get(args.length==0?"cache":args[0]));
        long start=System.currentTimeMillis();
        boolean generate=args.length>1&&args[1].equals("--generate");
        Native950EquipmentCatalogue c=generate?Native950EquipmentCatalogue.generate():Native950EquipmentCatalogue.current();
        require(c.entries.size()>200,"Catalogue must expand substantially beyond40");
        require(c.entries.size()<=700,"Native baseline capacity exceeded");
        if(!generate)require(Native950EquipmentCatalogue.current()==c,"Catalogue was not cached");
        if(!generate)Native950EquipmentLibraryAssets.verify();
        for(int category=0;category<c.counts.length;category++){
            require(c.counts[category]>0,"Empty category "+category);
            System.out.println("TAB "+category+" "+Native950EquipmentCatalogue.CATEGORIES[category]+" count="+c.counts[category]);
            for(Native950EquipmentCatalogue.Entry e:c.entries)if(e.category==category)
                System.out.println("  "+e.id+" T"+e.tier+" slot="+e.slot+" "+e.name+" group="+e.group);
        }
        for(Native950ContentCommands.ItemSearchEntry old:Native950ContentCommands.testingKitItemBrowserEntries())
            require(c.entries.stream().anyMatch(e->e.category==0&&e.id==old.id),"Lost old testing item "+old.id);
        for(String name:new String[]{"noxious","drygore","torva","rune","staff","arrow","necromancer"})
            require(c.entries.stream().anyMatch(e->e.name.toLowerCase(Locale.ROOT).contains(name)),"Missing useful search witness "+name);
        for(Native950EquipmentCatalogue.Entry e:c.entries){
            require(Native950CacheItems.entry(e.id)!=null,"Invalid catalogue identity");
            if(e.slot>=0)require(Native950EquipmentTypes.resolve(e.id)!=null,"Unusable equipment "+e.id);
            if(e.category!=0){String n=e.name.toLowerCase(Locale.ROOT);
                require(!n.contains("pickaxe")&&!n.contains("hatchet")&&!n.contains("mattock")&&!n.contains("master cape")
                        &&!n.startsWith("batch of ")&&!n.startsWith("deathmatch ")&&!n.contains("(broken)"),"Clutter admitted: "+e.name);}
        }
        require(c.counts[0]>=65,"Best tab needs a useful full first screen");
        for(int category=1;category<=5;category++){
            final int cat=category;List<Native950EquipmentCatalogue.Entry> tab=new ArrayList<>();
            for(Native950EquipmentCatalogue.Entry e:c.entries)if(e.category==cat)tab.add(e);
            int previousTier=Integer.MAX_VALUE;
            for(Native950EquipmentCatalogue.Entry e:tab)if(e.slot>=0&&e.slot!=13){
                require(e.tier<=previousTier,"Higher tier follows lower tier: "+category+" "+e.name);previousTier=e.tier;
            }
            Set<String> completed=new HashSet<>();String group=null;
            for(Native950EquipmentCatalogue.Entry e:tab){
                if(!e.group.equals(group)){require(!completed.contains(e.group),"Scattered equipment group "+e.group);if(group!=null)completed.add(group);group=e.group;}
            }
        }
        List<Native950EquipmentCatalogue.Entry> torva=new ArrayList<>();
        for(Native950EquipmentCatalogue.Entry e:c.entries)if(e.category==1&&e.group.equals("torva@80"))torva.add(e);
        require(torva.size()==5,"Torva set is incomplete");
        int[] armourSlots={0,4,7,9,10};for(int i=0;i<5;i++)require(torva.get(i).slot==armourSlots[i],"Armour set order changed");
        int main=-1,off=-1;for(int i=0;i<c.entries.size();i++){if(c.entries.get(i).id==26587)main=i;if(c.entries.get(i).id==26591)off=i;}
        require(off==main+1&&main>=0,"Drygore dual-wield pair is not adjacent");
        for(int id:new int[]{58036,58041,556,565,55337,55338,55339,55340})
            require(c.entries.stream().anyMatch(e->e.id==id&&e.quantity>=10000),"Missing resource stack "+id);
        if(generate){
            List<String> lines=new ArrayList<>();lines.add("# Generated by Native950EquipmentLibraryAcceptance cache --generate; do not hand-edit IDs. id/category/tier/slot/quantity/stackMode/name/group/sha256");
            for(Native950EquipmentCatalogue.Entry e:c.entries)lines.add(e.id+"\t"+e.category+"\t"+e.tier+"\t"+e.slot+"\t"+e.quantity+"\t"+e.stackMode+"\t"+e.name+"\t"+e.group+"\t"+Native950EquipmentCatalogue.hash(Cache.STORE.getIndexes()[19].getFile(e.id>>>8,e.id&255)));
            java.nio.file.Files.write(Paths.get("Ataraxia950/resources/native950/equipment-library-950.tsv"),lines,java.nio.charset.StandardCharsets.UTF_8);
            java.nio.file.Files.write(Paths.get("Ataraxia950/resources/native950/equipment-library-ui-950.properties"),Native950EquipmentLibraryAssets.generate(),java.nio.charset.StandardCharsets.UTF_8);
        }
        System.out.println("PASS: "+c.entries.size()+" cache-backed catalogue rows; build "+(System.currentTimeMillis()-start)+"ms; immutable cached result");
        System.out.println("LIMIT: native visual layout/search keyboard delivery still require the real950 client.");
    }
    private static void require(boolean value,String message){if(!value)throw new AssertionError(message);}
}
