package com.rs.game.player.client;
import com.rs.cache.Cache;import com.rs.cache.loaders.ItemDefinitions;import com.rs.cache.loaders.ObjectDefinitions;import com.rs.cache.loaders.VarBitDefinitions;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;
/** Explicit reviewed cache identity shared by the first-pass Farming/Construction ports. */
final class Native950FarmingConstructionAssets {
 private static final Properties PINS=new Properties();private static Object store;private static final Map<String,Boolean> checked=new HashMap<>();
 static{try(InputStream in=Native950FarmingConstructionAssets.class.getResourceAsStream("/native950/farming-construction-assets-950.properties")){if(in==null)throw new IllegalStateException("Missing farming/construction bindings");PINS.load(in);}catch(IOException e){throw new ExceptionInInitializerError(e);}}
 static List<String[]> rows(String resource){List<String[]> rows=new ArrayList<>();try(InputStream in=Native950FarmingConstructionAssets.class.getResourceAsStream("/native950/"+resource)){if(in==null)throw new IllegalStateException("Missing "+resource);BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8));String s;while((s=r.readLine())!=null)if(!s.isEmpty()&&!s.startsWith("#"))rows.add(s.split("\t"));}catch(IOException e){throw new IllegalStateException(e);}return rows;}
 static synchronized boolean pin(String kind,int id){if(Cache.STORE==null||!Cache.isFlatReadOnly())return false;if(store!=Cache.STORE){store=Cache.STORE;checked.clear();}String key=kind+"."+id;if(!checked.containsKey(key)){boolean valid=false;String hash=PINS.getProperty(key);if(hash!=null)try{int index=kind.equals("object")?16:kind.equals("item")?19:kind.equals("sequence")?20:kind.equals("struct")?22:2;int shift=kind.equals("sequence")?7:kind.equals("struct")?5:8;byte[] data=kind.equals("varp")?Cache.STORE.getIndexes()[2].getFile(60,id):kind.equals("varbit")?Cache.STORE.getIndexes()[2].getFile(69,id):Cache.STORE.getIndexes()[index].getFile(id>>>shift,id&((1<<shift)-1));if(data!=null){StringBuilder h=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(data))h.append(String.format("%02x",b&255));valid=hash.equals(h.toString());}}catch(Exception absent){valid=false;}checked.put(key,valid);}return checked.get(key);}
 static boolean item(int id){if(!pin("item",id))return false;ItemDefinitions d=ItemDefinitions.getItemDefinitions(id);return d.loaded&&d.name!=null&&!d.name.equals("null")&&!d.isNoted()&&!d.isLended();}
 static Native950ItemCatalog.Entry entry(int id){if(!item(id))return null;ItemDefinitions d=ItemDefinitions.getItemDefinitions(id);return new Native950ItemCatalog.Entry(id,d.name,d.isStackable(),new String[5]);}
 static List<Native950ItemCatalog.Entry> entries(){List<Native950ItemCatalog.Entry> r=new ArrayList<>();for(String key:PINS.stringPropertyNames())if(key.startsWith("item.")){Native950ItemCatalog.Entry e=entry(Integer.parseInt(key.substring(5)));if(e!=null)r.add(e);}return Collections.unmodifiableList(r);}
 static void verify(){for(String key:PINS.stringPropertyNames()){int dot=key.indexOf('.');if(!pin(key.substring(0,dot),Integer.parseInt(key.substring(dot+1))))throw new IllegalStateException("Changed farming/construction cache asset "+key);}}
}
