package com.rs.game.player.client;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.Charset;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.TreeMap;

/**
 * The 910 -&gt; 950 id validity table, and the only question the rest of the server asks it:
 * <b>may this id be acted on?</b>
 *
 * <p>Ataraxia's JSON data - spawns, drops, shops, bonuses, stats - is keyed by <b>910</b>
 * definition ids, but the client and every definition served to it come from the 950 cache.
 * The two numbering spaces overlap without agreeing. Three failure modes exist and only one
 * of them is loud:
 *
 * <ul>
 * <li>the id has no 950 definition: the loaders already serve a placeholder, so it is
 *     visible;</li>
 * <li>the id names the same thing under a new string: harmless to look at, but nothing may
 *     assume its old fields;</li>
 * <li><b>the id now names something else entirely, and loads perfectly.</b> NPC 42 is a
 *     Sheep in the 910 cache and "Bill" in the 950 one; item 1079 keeps the name "Rune
 *     platelegs" and loses its equipment slot. Spawning that is silently wrong.</li>
 * </ul>
 *
 * <p>The table is generated by {@code com.rs.tools.modern.IdValidityProbe} from both caches
 * and checked in at {@link #RESOURCE}; this class only reads it. It is deliberately
 * incapable of guessing: an id it has no row for is {@link Verdict#UNCLASSIFIED} and
 * therefore unsafe, exactly like a repurposed one.
 *
 * <p><b>{@link Verdict#SAME} and {@link Verdict#RESTYLED} are safe, and nothing else is.</b>
 * {@code restyled} means the two names are equal ignoring case and unequal exactly - the 950
 * move to sentence case, "Hill Giant" to "Hill giant" - while every other compared field is
 * still identical. The owner admitted it on 2026-09-07; it recovers 89 refused spawn rows,
 * 35 of them NPC 117 and 14 NPC 1265. It is the narrowest loosening available: the probe
 * decides it with {@link String#equalsIgnoreCase}, not with the similarity heuristic, and it
 * runs every field check {@code same} runs, so a case-only rename whose size or option array
 * also moved is still {@code repurposed}.
 *
 * <p>{@code renamed} and {@code repurposed} stay refused; the split between them is a
 * readability aid the probe computes from a string-similarity rule and no decision here
 * depends on it.
 *
 * <p>Coverage differs by kind and is published as {@link #coverage(Kind)}: NPC rows cover
 * the whole of both cache indexes, so any NPC id can be asked about; item and object rows
 * cover only the ids Ataraxia's data files reference, so an unreferenced item id answers
 * {@code UNCLASSIFIED} - which is refused, which is the correct answer for a caller that
 * should have been reading the cache directly.
 */
public final class Native950IdValidity {

    /**
     * Generated directly from the legacy 910 definition dump and the paired 950 cache.
     * This gate applies to every published native NPC, even with data spawns disabled.
     * Only SAME/RESTYLED remain safe; refreshed identities do not enable combat or AI.
     * See protocol-analysis/id-validity/ for inputs and the generated report.
     */
    public static final String RESOURCE = "/native950/id-validity-950.json";
    /** Bumped to 2 with the {@code restyled} bucket; a format-1 table cannot carry one. */
    public static final int FORMAT = 2;
    public static final int REVISION = 950;
    private static final Charset UTF8 = Charset.forName("UTF-8");

    /**
     * The verdicts this loader will act on, in the order the table must declare them. Every
     * other verdict is refused. Keep in step with {@code IdValidityProbe}'s safeVerdicts.
     */
    private static final String[] SAFE_VERDICTS = { "same", "restyled" };

    /** The trusted set, copied so a caller cannot edit the policy in place. */
    public static String[] safeVerdicts() { return SAFE_VERDICTS.clone(); }

    /** The definition families the table classifies. */
    public enum Kind {
        NPC("npc"), ITEM("item"), OBJECT("object");
        private final String key;
        Kind(String key) { this.key = key; }
        public String key() { return key; }
    }

    /** How an id fared between the two caches. Only {@link #SAME} and {@link #RESTYLED} are safe. */
    public enum Verdict {
        /** The 950 definition exists and every compared field agrees. */
        SAME,
        /**
         * Every compared field agrees and the names differ in letter case only, e.g.
         * "Hill Giant" to "Hill giant". Safe: case cannot change what a definition denotes,
         * and the size, equipment and option checks all ran and all passed.
         */
        RESTYLED,
        /** The 950 definition exists and reads as the same thing under a different name. */
        RENAMED,
        /** The 950 definition exists and is something else, or lost a field that matters. */
        REPURPOSED,
        /** No usable 950 definition. */
        MISSING,
        /** No 910 definition to compare against, so nothing can be concluded. */
        UNVERIFIABLE,
        /** The table has no row for this id at all. */
        UNCLASSIFIED;

        public boolean isSafe() { return this == SAME || this == RESTYLED; }
    }

    /** One kind's verdict tallies, as the probe measured them. */
    public static final class Counts {
        public final int total, same, restyled, renamed, repurposed, missing, unverifiable;
        Counts(int total, int same, int restyled, int renamed, int repurposed, int missing, int unverifiable) {
            this.total = total; this.same = same; this.restyled = restyled; this.renamed = renamed;
            this.repurposed = repurposed; this.missing = missing; this.unverifiable = unverifiable;
        }
        /** Everything a caller may act on: {@code same} plus {@code restyled}. */
        public int safe() { return same + restyled; }
        @Override public String toString() {
            return "total=" + total + ",same=" + same + ",restyled=" + restyled + ",renamed=" + renamed
                    + ",repurposed=" + repurposed + ",missing=" + missing + ",unverifiable=" + unverifiable;
        }
    }

    /** One kind's rows. Range sets are inclusive [from,to] pairs, ascending and disjoint. */
    private static final class Rows {
        final int[] same, missing, unverifiable;
        final Map<Integer, String> restyled, renamed, repurposed;
        final Counts scanned, referenced;
        final String coverage;
        Rows(int[] same, int[] missing, int[] unverifiable, Map<Integer, String> restyled,
             Map<Integer, String> renamed, Map<Integer, String> repurposed,
             Counts scanned, Counts referenced, String coverage) {
            this.same = same; this.missing = missing; this.unverifiable = unverifiable;
            this.restyled = Collections.unmodifiableMap(restyled);
            this.renamed = Collections.unmodifiableMap(renamed);
            this.repurposed = Collections.unmodifiableMap(repurposed);
            this.scanned = scanned; this.referenced = referenced; this.coverage = coverage;
        }
    }

    private final Map<Kind, Rows> rows;
    private final String legacyCache, modernCache;

    private Native950IdValidity(Map<Kind, Rows> rows, String legacyCache, String modernCache) {
        this.rows = rows;
        this.legacyCache = legacyCache;
        this.modernCache = modernCache;
    }

    // ------------------------------------------------------------------ loading

    private static volatile Native950IdValidity instance;

    /**
     * The checked-in table, loaded once. Throws when the resource is absent or malformed;
     * a server that cannot tell a Sheep from a Bill must not start spawning either.
     */
    public static Native950IdValidity get() {
        Native950IdValidity loaded = instance;
        if (loaded != null) return loaded;
        synchronized (Native950IdValidity.class) {
            if (instance == null) instance = loadResource();
            return instance;
        }
    }

    private static Native950IdValidity loadResource() {
        InputStream in = Native950IdValidity.class.getResourceAsStream(RESOURCE);
        if (in == null)
            throw new IllegalStateException("950 id validity table " + RESOURCE
                    + " is not on the classpath (resources/ must be packaged)");
        try {
            Reader text = new InputStreamReader(in, UTF8);
            try { return load(text); } finally { text.close(); }
        } catch (java.io.IOException failure) {
            throw new IllegalStateException("Cannot read " + RESOURCE, failure);
        }
    }

    /** Loads a table from JSON text; used by the tests with a small fixture. */
    public static Native950IdValidity load(Reader json) {
        JsonElement parsed = JsonParser.parseReader(json);
        if (parsed == null || !parsed.isJsonObject())
            throw new IllegalStateException("The 950 id validity table must be a JSON object");
        JsonObject root = parsed.getAsJsonObject();
        int format = required(root, "format").getAsInt();
        if (format != FORMAT)
            throw new IllegalStateException("Unsupported id validity table format " + format + "; expected " + FORMAT);
        int revision = required(root, "revision").getAsInt();
        if (revision != REVISION)
            throw new IllegalStateException("The id validity table is for revision " + revision + ", not " + REVISION);
        // The trusted set is pinned, not merely checked for membership: a regenerated table
        // that widened the policy - or narrowed it - must not be adopted silently. Adding a
        // verdict here is a deliberate two-file change, exactly as 'restyled' was.
        JsonElement safe = required(root, "safeVerdicts");
        if (!safe.isJsonArray() || safe.getAsJsonArray().size() != SAFE_VERDICTS.length)
            throw new IllegalStateException("This loader trusts exactly " + SAFE_VERDICTS.length
                    + " verdicts; the table declares " + safe);
        for (int i = 0; i < SAFE_VERDICTS.length; i++)
            if (!safe.getAsJsonArray().get(i).getAsString().equals(SAFE_VERDICTS[i]))
                throw new IllegalStateException("This loader trusts " + java.util.Arrays.toString(SAFE_VERDICTS)
                        + " in that order; the table declares " + safe);

        JsonObject kinds = required(root, "kinds").getAsJsonObject();
        Map<Kind, Rows> rows = new LinkedHashMap<Kind, Rows>();
        for (Kind kind : Kind.values()) {
            if (!kinds.has(kind.key()))
                throw new IllegalStateException("The id validity table has no rows for " + kind.key());
            rows.put(kind, rows(kind, kinds.getAsJsonObject(kind.key())));
        }
        return new Native950IdValidity(rows,
                root.has("legacyCache") ? root.get("legacyCache").getAsString() : "",
                root.has("modernCache") ? root.get("modernCache").getAsString() : "");
    }

    private static Rows rows(Kind kind, JsonObject section) {
        int[] same = ranges(kind, "same", text(section, "same"));
        int[] missing = ranges(kind, "missing", text(section, "missing"));
        int[] unverifiable = ranges(kind, "unverifiable", text(section, "unverifiable"));
        Map<Integer, String> restyled = reasons(section, "restyled");
        Map<Integer, String> renamed = reasons(section, "renamed");
        Map<Integer, String> repurposed = reasons(section, "repurposed");
        // An id in two buckets would make the answer depend on lookup order - and with
        // 'restyled' now safe, an id in both 'restyled' and 'repurposed' would make it depend
        // on lookup order whether the id may be spawned at all.
        for (Integer id : restyled.keySet())
            exclusive(kind, id.intValue(), same, missing, unverifiable, renamed, repurposed);
        for (Integer id : renamed.keySet())
            exclusive(kind, id.intValue(), same, missing, unverifiable, restyled, repurposed);
        for (Integer id : repurposed.keySet())
            exclusive(kind, id.intValue(), same, missing, unverifiable, restyled, renamed);
        return new Rows(same, missing, unverifiable, restyled, renamed, repurposed,
                counts(section, "scanned"), counts(section, "referenced"),
                section.has("coverage") ? section.get("coverage").getAsString() : "unknown");
    }

    private static void exclusive(Kind kind, int id, int[] a, int[] b, int[] c,
                                  Map<Integer, String> d, Map<Integer, String> e) {
        if (contains(a, id) || contains(b, id) || contains(c, id)
                || d.containsKey(Integer.valueOf(id)) || e.containsKey(Integer.valueOf(id)))
            throw new IllegalStateException("The id validity table classifies " + kind.key() + " " + id + " twice");
    }

    private static Counts counts(JsonObject section, String name) {
        if (!section.has(name)) return new Counts(0, 0, 0, 0, 0, 0, 0);
        JsonObject o = section.getAsJsonObject(name);
        return new Counts(count(o, "total"), count(o, "same"), count(o, "restyled"), count(o, "renamed"),
                count(o, "repurposed"), count(o, "missing"), count(o, "unverifiable"));
    }

    private static int count(JsonObject o, String key) {
        return o.has(key) && !o.get(key).isJsonNull() ? o.get(key).getAsInt() : 0;
    }

    private static Map<Integer, String> reasons(JsonObject section, String name) {
        Map<Integer, String> out = new TreeMap<Integer, String>();
        if (!section.has(name) || section.get(name).isJsonNull()) return out;
        for (Map.Entry<String, JsonElement> entry : section.getAsJsonObject(name).entrySet()) {
            Integer id = Integer.valueOf(entry.getKey());
            if (out.put(id, entry.getValue().getAsString()) != null)
                throw new IllegalStateException("Duplicate " + name + " row for id " + id);
        }
        return out;
    }

    private static String text(JsonObject section, String key) {
        return section.has(key) && !section.get(key).isJsonNull() ? section.get(key).getAsString() : "";
    }

    private static JsonElement required(JsonObject root, String key) {
        JsonElement value = root.get(key);
        if (value == null || value.isJsonNull())
            throw new IllegalStateException("The 950 id validity table needs a \"" + key + "\" field");
        return value;
    }

    /**
     * Parses "0-41,44,46-99" into ascending, disjoint inclusive pairs. The whole-index NPC
     * "same" set is over twenty thousand ids; ranges keep the checked-in table readable.
     * Anything out of order, overlapping or backwards rejects the whole table, because a
     * silently mis-parsed range would answer "safe" for ids nobody classified.
     */
    static int[] ranges(Kind kind, String name, String encoded) {
        String trimmed = encoded.trim();
        if (trimmed.length() == 0) return new int[0];
        String[] parts = trimmed.split(",");
        int[] pairs = new int[parts.length * 2];
        int previousTo = Integer.MIN_VALUE;
        for (int i = 0; i < parts.length; i++) {
            String part = parts[i].trim();
            int dash = part.indexOf('-', 1);
            int from, to;
            try {
                from = Integer.parseInt(dash < 0 ? part : part.substring(0, dash));
                to = dash < 0 ? from : Integer.parseInt(part.substring(dash + 1));
            } catch (NumberFormatException bad) {
                throw new IllegalStateException("Malformed " + kind.key() + " " + name + " range \"" + part + "\"");
            }
            if (to < from)
                throw new IllegalStateException("Backwards " + kind.key() + " " + name + " range \"" + part + "\"");
            if (previousTo != Integer.MIN_VALUE && from <= previousTo)
                throw new IllegalStateException("Out-of-order or overlapping " + kind.key() + " " + name
                        + " range \"" + part + "\"");
            pairs[i * 2] = from;
            pairs[i * 2 + 1] = to;
            previousTo = to;
        }
        return pairs;
    }

    private static boolean contains(int[] pairs, int id) {
        int low = 0, high = pairs.length / 2 - 1;
        while (low <= high) {
            int mid = (low + high) >>> 1;
            if (id < pairs[mid * 2]) high = mid - 1;
            else if (id > pairs[mid * 2 + 1]) low = mid + 1;
            else return true;
        }
        return false;
    }

    // ------------------------------------------------------------------ questions

    /** The one question callers should ask. True only for {@link Verdict#SAME}. */
    public boolean isSafe(Kind kind, int id) {
        return verdict(kind, id).isSafe();
    }

    public Verdict verdict(Kind kind, int id) {
        if (kind == null) throw new IllegalArgumentException("kind");
        Rows section = rows.get(kind);
        if (id < 0) return Verdict.UNCLASSIFIED;
        if (contains(section.same, id)) return Verdict.SAME;
        Integer key = Integer.valueOf(id);
        if (section.repurposed.containsKey(key)) return Verdict.REPURPOSED;
        if (section.renamed.containsKey(key)) return Verdict.RENAMED;
        if (section.restyled.containsKey(key)) return Verdict.RESTYLED;
        if (contains(section.missing, id)) return Verdict.MISSING;
        if (contains(section.unverifiable, id)) return Verdict.UNVERIFIABLE;
        return Verdict.UNCLASSIFIED;
    }

    /**
     * Why an id is what it is, in one line fit for a log. Never empty for an unsafe id: a
     * skipped spawn must always be able to say what it was and what the id became.
     */
    public String reason(Kind kind, int id) {
        Verdict verdict = verdict(kind, id);
        Rows section = rows.get(kind);
        switch (verdict) {
            case SAME:
                return "950 definition matches the 910 one";
            case RESTYLED:
                return "case-only rename in 950: " + section.restyled.get(Integer.valueOf(id));
            case RENAMED:
                return "renamed in 950: " + section.renamed.get(Integer.valueOf(id));
            case REPURPOSED:
                return "repurposed in 950: " + section.repurposed.get(Integer.valueOf(id));
            case MISSING:
                return "no usable 950 definition";
            case UNVERIFIABLE:
                return "no 910 definition to compare against";
            default:
                return "not classified by the 950 validity table (" + section.coverage + " coverage)";
        }
    }

    public Counts scanned(Kind kind) { return rows.get(kind).scanned; }

    public Counts referenced(Kind kind) { return rows.get(kind).referenced; }

    /** "whole-index" or "referenced-ids-only": which ids this kind's rows cover. */
    public String coverage(Kind kind) { return rows.get(kind).coverage; }

    public String legacyCache() { return legacyCache; }

    public String modernCache() { return modernCache; }

    @Override public String toString() {
        StringBuilder text = new StringBuilder("Native950IdValidity[");
        boolean first = true;
        for (Kind kind : Kind.values()) {
            if (!first) text.append(' ');
            first = false;
            text.append(kind.key()).append('{').append(rows.get(kind).scanned).append('}');
        }
        return text.append(']').toString();
    }
}
