"""Reproduce bounded950 boss assets using pinned949 names and equal sequence payloads.
Cache and exported names are read only; downloads stay in temp/gameval-research.
"""
import sys,json,hashlib,urllib.request
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from verify_950_player_effects import Cache,Reader
from generate_950_npc_combat_animations import sequence
root=Path(__file__).resolve().parents[2]
inputs=root/'temp/gameval-research'
namesraw=(inputs/'2670-seq.txt').read_bytes()
if hashlib.sha256(namesraw).hexdigest()!='8ee30d038c06be125fb484be3968e281355f48601de3726b1e5db6654fa6d5e8':raise ValueError('Named source changed')
names=dict((int(k),v) for k,v in (line.split('\t',1) for line in namesraw.decode().splitlines() if line))
ids=[17361,17362,17389,17391,29366,29371,29375,29378,29380,29381,29382,29383,29373,29374]
for index,group in [(255,20)]+[(20,g) for g in sorted({i>>7 for i in ids})]:
 p=inputs/f'beta-cache/{index}/{group}.dat'
 if not p.exists():
  raw=urllib.request.urlopen(f'https://archive.openrs2.org/caches/runescape/2670/archives/{index}/groups/{group}.dat',timeout=20).read()
  p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(raw)
old=Cache(inputs/'beta-cache',True);new=Cache(root/'cache',True)
sha=lambda b:hashlib.sha256(b).hexdigest()
rows=[];anims=[];evidence=[]
for id in ids:
 a=old.archive(20,id>>7)[id&127];b=new.archive(20,id>>7)[id&127]
 if a!=b:raise ValueError(f'Sequence {id} differs from named source')
 duration=sequence(b)['durationCycles']
 rows.append(('sequence',id,names[id],20,id>>7,id&127,sha(b),'949 exported name; sequence payload identical in950',sha(new.raw(255,20))))
 anims.append(f'{id}={sha(b)},{duration},identical-definition')
 evidence.append(dict(id=id,name=names[id],sha256=sha(b),durationCycles=duration))
for id,seq in [(6355,29380),(6356,29381),(6357,29382),(6358,29374),(6359,29373),(3352,17362)]:
 b=new.archive(21,id>>8)[id&255];r=Reader(b);fields={}
 for _ in range(2):
  op=r.integer(1)
  if op not in (1,2):raise ValueError('Unexpected spotanim prefix')
  fields[op]=r.smart(7)
 if fields[2]!=seq:raise ValueError('Wrong effect sequence')
 rows.append(('effect',id,'shnorkscape_'+names[seq],21,id>>8,id&255,sha(b),'Project effect alias from exact950 linked named sequence',sha(new.raw(255,21))))
 evidence.append(dict(effect=id,sequence=seq,model=fields[1],sha256=sha(b)))
resources=root/'Ataraxia950/resources/native950'
(resources/'boss-symbols-950.tsv').write_text('# Generated by tools/combat-pass/build_boss_bindings.py; names are949 evidence, numeric bindings are checked950.\n'+''.join('\t'.join(map(str,r))+'\n' for r in rows),newline='\n')
(resources/'boss-animations-950.properties').write_text('# Generated: exact949/950 sequence equality, original named role retained.\n'+'\n'.join(anims)+'\n',newline='\n')
(root/'protocol-analysis/boss-bindings-950-20260924.json').write_text(json.dumps(dict(nameSource='https://gameval.z-kris.com/site/gameval/runescape/2670/seq.txt',nameSourceSha256=sha(namesraw),sourceCache=2670,targetCache=2691,bindings=evidence,limitation='Payload/role proof, not physical Vulkan acceptance'),indent=2)+'\n',newline='\n')
print('Generated',len(rows),'symbols and',len(anims),'sequence bindings')
