"""Generate V4 capture artifacts without replacing the live-proven V3 schema."""
import hashlib
import json
from snapshot_schema import HERE
from restore_schema import schema

def artifacts():
    s=schema()
    data=(json.dumps(s,sort_keys=True,separators=(',',':'))+'\n').encode()
    header='// Generated by generate_v4_schema.py; do not edit.\n#pragma once\n'
    header+='static const char* schemaHash = "'+hashlib.sha256(data).hexdigest()+'";\n'
    header+='static const int workspaceIds[] = {'+','.join(map(str,s['ids']))+'};\n'
    return data,header

if __name__=='__main__':
    data,header=artifacts()
    (HERE/'snapshot-schema-v4.json').write_bytes(data)
    (HERE/'snapshot-schema-v4.h').write_text(header,encoding='ascii')
    print('912 IDs; schema file SHA256 '+hashlib.sha256(data).hexdigest())
