"""Generate a bounded, read-only symbol index from audited original names.
No guessed IDs: whole identical interface groups or explicitly audited variable files.
Run: python tools/build_gameval_lookup_950.py --inputs temp/gameval-research --cache cache --output <tsv>
"""
import argparse, hashlib, json
from pathlib import Path
from research_gamevals_950 import decode_gameval
from build_necromancy_polish_cache import unpack

def build(inputs, cache, audit):
    maps={}
    for g,t in ((0,"component"),(24,"interface"),(61,"var_player")):
        raw=unpack((inputs/f"2670-67-{g}.dat").read_bytes())
        expected=next(x["rawSha256"] for x in audit["rawDecoderChecks"] if x["type"]==t)
        if hashlib.sha256(raw).hexdigest()!=expected:raise ValueError("Original name source changed")
        maps[t]=decode_gameval(raw,t=="component")
    rows=[]
    for group in audit["groupComparisons"]:
        if not group["identical950"] or group["index"]!=3:continue
        g=group["group"]; source=(inputs/f"2670-3-{g}.dat").read_bytes();target=(cache/"3"/f"{g}.dat").read_bytes()
        if unpack(source)!=unpack(target) or hashlib.sha256(unpack(source)).hexdigest()!=group["sha256"]:raise ValueError(f"Interface {g} changed")
        rows.append(("interface",str(g),maps["interface"][g],3,g,-1,hashlib.sha256(target).hexdigest(),"Whole interface group identical to 949 source"))
        for key,name in maps["component"].items():
            if key>>16==g:rows.append(("component",f"{g}:{key&65535}",name,3,g,-1,hashlib.sha256(target).hexdigest(),"Whole interface group identical to 949 source"))
    offset=min(k for k,v in maps["var_player"].items() if v.startswith("_"))
    for row in audit["productionReaderComparisonRows"]:
        if row[0]!="FILE" or row[1]!="2" or row[4]!="true":continue
        group,id=int(row[2]),int(row[3]);typ="varp" if group==60 else "varbit"
        name=maps["var_player"][id if group==60 else id+offset].lstrip("_")
        # Payload equality alone does not prove semantics; retain this weaker evidence explicitly.
        rows.append((typ,str(id),name,2,group,id,row[6],"949 name; audited 950 variable payload match"))
    keys=set();names=set()
    for row in rows:
        key=(row[0],row[1]);name=(row[0],row[2])
        if key in keys or name in names:raise ValueError("Symbol collision")
        keys.add(key);names.add(name)
    rows=[r+(hashlib.sha256((cache/"255"/f"{r[3]}.dat").read_bytes()).hexdigest(),) for r in rows]
    return sorted(rows,key=lambda r:(r[0],r[2],r[1]))

def main():
    p=argparse.ArgumentParser();p.add_argument("--inputs",type=Path,required=True);p.add_argument("--cache",type=Path,required=True);p.add_argument("--output",type=Path,required=True);a=p.parse_args()
    audit=json.loads(Path("protocol-analysis/gameval-investigation-950.json").read_bytes())
    rows=build(a.inputs,a.cache,audit)
    header="# Generated by tools/build_gameval_lookup_950.py; do not edit. Source OpenRS2 2670 (949); target 2691 (950.1).\n# Read-only lookup, not a runtime binding API. Evidence and live hash validation are mandatory.\n"
    a.output.write_bytes((header+"".join("\t".join(map(str,r))+"\n" for r in rows)).encode("utf-8"))
    print(f"Generated {len(rows)} audited symbols")
if __name__=="__main__":main()
