package com.rs.game.player.client;
import com.google.gson.*;import java.nio.charset.StandardCharsets;import com.rs.cache.Cache;import com.rs.cache.loaders.*;import com.rs.cache.loaders.rs3.RS3GeneralRequirementMap;import java.nio.file.*;import java.io.*;import java.util.*;import java.security.MessageDigest;
public class Native950InventionAssetDump {
 static Properties pins=new Properties();static void pin(String kind,int id,int idx,int shift)throws Exception{byte[] b=Cache.STORE.getIndexes()[idx].getFile(id>>>shift,id&((1<<shift)-1));if(b==null)throw new Exception("Missing "+kind+id);StringBuilder s=new StringBuilder();for(byte x:MessageDigest.getInstance("SHA-256").digest(b))s.append(String.format("%02x",x&255));pins.setProperty(kind+"."+id,s.toString());}
 public static void main(String[] a)throws Exception{Cache.initFlatReadOnly(Paths.get(a[0]));Path file=Paths.get(a[1]);try(InputStream in=Files.newInputStream(file)){pins.load(in);}for(int id:new int[]{36389,36719,36721,36723,36725,36730,36390,41073}){ItemDefinitions d=ItemDefinitions.getItemDefinitions(id);System.out.println(id+" "+d.name+" "+d.clientScriptData);for(int i=0;i<10;i++){int item=d.getCSOpcode(2655+i,0);if(item>0&&item!=36365)pin("item",item,19,8);}int struct=d.getCSOpcode(2675,0);if(struct>0){pin("struct",struct,22,5);RS3GeneralRequirementMap map=RS3GeneralRequirementMap.getMap(struct);for(int i=0;i<10;i++){int item=map.getIntValue(2655+i);if(item>0){pin("item",item,19,8);System.out.println(" alternative="+item+" amount="+map.getIntValue(2665+i));}}}}
 try(OutputStream out=Files.newOutputStream(file)){pins.store(out,"Paired950 definitions; identity matched ordinary910 disassembly source.");}
 for(int mattock:new int[]{49574,49581,49584})pin("item",mattock,19,8);try(OutputStream out=Files.newOutputStream(file)){pins.store(out,"Paired950 definitions; identity matched ordinary910 disassembly source.");}Path rows=file.getParent().resolve("invention-disassembly-950.json"); Gson gson=new Gson(); JsonArray json=new JsonParser().parse(new String(Files.readAllBytes(rows),StandardCharsets.UTF_8)).getAsJsonArray(); Map<String,Integer> ids=new HashMap<>(); for(int n=0;n<ClientScriptMap.getMap(10742).getSize();n++)ids.put(InventionDefinitions.getMaterialName(n).toLowerCase(Locale.ROOT),n); for(JsonElement row:json)for(JsonElement component:row.getAsJsonObject().getAsJsonObject("data").getAsJsonArray("components")){JsonObject c=component.getAsJsonObject();Integer idx=ids.get(c.get("name").getAsString().toLowerCase(Locale.ROOT));if(idx==null)throw new Exception("Missing material "+c);c.addProperty("id",idx);}Files.write(rows,gson.toJson(json).getBytes(StandardCharsets.UTF_8));Native950Invention.verifyCacheBindings();Native950Archaeology.verifyCacheBindings();System.out.println("PASS "+Native950Invention.recipes().size()+" Invention, "+Native950Archaeology.recipes().size()+" Archaeology recipes; pins="+pins.size());}
}



