package com.rs.game.player.client;
import com.rs.cache.Cache;import com.rs.cache.loaders.*;import com.rs.cache.loaders.rs3.RS3GeneralRequirementMap;import com.rs.game.player.FarmingManager;import com.rs.game.player.content.construction.HouseConstants.HObject;import com.rs.game.item.Item;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.lang.reflect.Field;import java.util.*;
public final class Native950FarmingConstructionAssetDump {
 static final Map<String,String> pins=new TreeMap<>();static final Map<Integer,Integer> patches=new TreeMap<>();static final Map<Integer,List<Integer>> cropValues=new TreeMap<>();
 static Object field(Object o,String n)throws Exception{Field f=o.getClass().getDeclaredField(n);f.setAccessible(true);return f.get(o);}static int number(Object o,String n)throws Exception{return ((Number)field(o,n)).intValue();}
 static void pin(String k,int id,int index,int group,int file)throws Exception {byte[] b=Cache.STORE.getIndexes()[index].getFile(group,file);if(b==null)throw new IllegalStateException(k+id);StringBuilder h=new StringBuilder();for(byte v:MessageDigest.getInstance("SHA-256").digest(b))h.append(String.format("%02x",v&255));pins.put(k+"."+id,h.toString());}
 static void pin(String k,int id,int index,int shift)throws Exception{pin(k,id,index,id>>>shift,id&((1<<shift)-1));}static void item(int id)throws Exception{if(id>0)pin("item",id,19,8);}
 static boolean op(ObjectDefinitions d,String s){return d.options!=null&&Arrays.stream(d.options).anyMatch(s::equalsIgnoreCase);}
 public static void main(String[] a)throws Exception{Path root=Paths.get(a[0]);Cache.initFlatReadOnly(root.resolve("cache"));List<String> cropRows=new ArrayList<>(),patchRows=new ArrayList<>(),furniture=new ArrayList<>(),varRows=new ArrayList<>();
  Map<Integer,Integer> representative=new HashMap<>();representative.put(0,8550);representative.put(2,8173);representative.put(3,7847);representative.put(6,8150);
  for(FarmingManager.ProductInfo c:FarmingManager.ProductInfo.values()){int type=number(c,"type");if(!representative.containsKey(type)||c.productId<=0||c.name().equals("SnapeGrass"))continue;int seed=number(c,"seedId");String name=ItemDefinitions.getItemDefinitions(seed).name.toLowerCase(Locale.ROOT).replace(" seed"," ").trim();if(name.equals("gout tuber"))name="goutweed";if(name.equals("limpwurt"))name="limpwurt";String normalized=name.replace(" ","");ObjectDefinitions base=ObjectDefinitions.getObjectDefinitions(representative.get(type));int end=-1;
   for(int i=4;i<Math.min(128,base.transforms.length-1);i++){int id=base.transforms[i];if(id<0)continue;ObjectDefinitions d=ObjectDefinitions.getObjectDefinitions(id);String current=d.name.toLowerCase(Locale.ROOT).replace(" ","");if(current.startsWith(normalized)&&(op(d,"Pick")||op(d,"Harvest"))){end=i;break;}}
   if(end<0){System.out.println("SKIP crop "+c.name()+" no current harvest morph for "+name);continue;}
   int start=end;while(start>4){ObjectDefinitions d=ObjectDefinitions.getObjectDefinitions(base.transforms[start-1]);String current=d.name.toLowerCase(Locale.ROOT).replace(" ","");if(!current.startsWith(normalized)||op(d,"Pick")||op(d,"Harvest"))break;start--;}
   int stages=end-start;if(stages<1){System.out.println("SKIP crop "+c.name()+" stages="+stages);continue;}
   long minutes=number(c,"cycleTime")*number(c,"maxStage")*(type==6?2:1);int amount=type==0||type==2?3:1;
   cropRows.add(seed+"\t"+type+"\t"+number(c,"level")+"\t"+c.productId+"\t"+field(c,"plantingExperience")+"\t"+field(c,"experience")+"\t"+minutes+"\t"+amount+"\t"+start+"\t"+stages);item(seed);item(c.productId);List<Integer> values=cropValues.computeIfAbsent(type,k->new ArrayList<>());for(int i=start;i<=end;i++)values.add(i);
  }
  for(FarmingManager.SpotInfo s:FarmingManager.SpotInfo.values()){int type=number(s,"type");if(!representative.containsKey(type))continue;int id=number(s,"objectId");ObjectDefinitions d=ObjectDefinitions.getObjectDefinitions(id),reference=ObjectDefinitions.getObjectDefinitions(representative.get(type));if(d.transforms==null||d.configFileId<0||!Arrays.equals(d.transforms,reference.transforms)){System.out.println("SKIP patch "+s.name()+" different morph table");continue;}pin("object",id,16,8);pin("varbit",d.configFileId,2,69,d.configFileId);VarBitDefinitions bit=VarBitDefinitions.getClientVarpBitDefinitions(d.configFileId);pin("varp",bit.baseVar,2,60,bit.baseVar);varRows.add(id+"\t"+d.configFileId+"\t"+bit.baseVar+"\t"+bit.startBit+"\t"+bit.endBit);for(int i=0;i<4;i++)pin("object",d.transforms[i],16,8);for(int i:cropValues.getOrDefault(type,Collections.emptyList()))pin("object",d.transforms[i],16,8);patchRows.add(id+"\t"+type);}
  Map<String,Integer> currentFurniture=new TreeMap<>();for(int id=61929;id<62120;id++){ItemDefinitions d=ItemDefinitions.getItemDefinitions(id);if(d.loaded&&!d.isNoted()&&d.getCSOpcode(2640,0)==22&&d.getCSOpcode(2655,0)>0)currentFurniture.put(d.name.toLowerCase(Locale.ROOT),id);}
  for(HObject old:HObject.values()){ItemDefinitions icon=ItemDefinitions.getItemDefinitions(old.getItemId());Integer id=currentFurniture.get(icon.name.toLowerCase(Locale.ROOT));if(id==null)continue;ItemDefinitions d=ItemDefinitions.getItemDefinitions(id);boolean valid=true;for(int i=0;i<10;i++){int input=d.getCSOpcode(2655+i,0);if(input>0)item(input);int struct=d.getCSOpcode(2675+i,0);if(struct>0){pin("struct",struct,22,5);RS3GeneralRequirementMap map=RS3GeneralRequirementMap.getMap(struct);boolean found=false;for(Item preferred:old.getRequirements())for(int n=0;n<10;n++)if(map.getIntValue(2655+n)==preferred.getId()){found=true;item(preferred.getId());}valid&=found;}}
   if(!valid){System.out.println("SKIP furniture "+old.name()+" unavailable ingredient alternative");continue;}item(id);item(old.getItemId());for(int i=0;i<3;i++)item(d.getCSOpcode(2650+i,0));furniture.add(old.name()+"\t"+id);}
  for(int id:new int[]{5325,5341,5343,952,6032,6034,43966,1925,6055,2347,8794})item(id);
  for(int id:new int[]{2273,2291,830,2282,2292,3683})pin("sequence",id,20,7);
  List<String> stations=new ArrayList<>();for(String line:Files.readAllLines(root.resolve("dumps/objects.txt"),StandardCharsets.UTF_8)){String[] cols=line.split("\t");if(cols.length<2||!cols[0].matches("[0-9]+")||!cols[1].toLowerCase(Locale.ROOT).contains("workbench"))continue;int id=Integer.parseInt(cols[0]);ObjectDefinitions d=ObjectDefinitions.getObjectDefinitions(id);if(d.transforms==null&&(("Furniture workbench".equals(d.name)&&op(d,"Construct"))||(id>=13704&&id<=13708&&op(d,"Work-at")))){pin("object",id,16,8);stations.add(id+"\t"+d.name+"\t"+Arrays.toString(d.options));}}
  Files.write(root.resolve("protocol-analysis/farming-vars-950.tsv"),varRows,StandardCharsets.UTF_8);Path resources=root.resolve("Ataraxia950/resources/native950");Files.write(resources.resolve("farming-crops-950.tsv"),cropRows,StandardCharsets.UTF_8);Files.write(resources.resolve("farming-patches-950.tsv"),patchRows,StandardCharsets.UTF_8);Files.write(resources.resolve("construction-furniture-950.tsv"),furniture,StandardCharsets.UTF_8);List<String> pp=new ArrayList<>();pp.add("# Reviewed 950 cache bindings for original Farming crops and Construction furniture.");for(Map.Entry<String,String> e:pins.entrySet())pp.add(e.getKey()+"="+e.getValue());Files.write(resources.resolve("farming-construction-assets-950.properties"),pp,StandardCharsets.UTF_8);Files.write(root.resolve("protocol-analysis/farming-construction-stations-950.tsv"),stations,StandardCharsets.UTF_8);System.out.println("PASS bindings: "+cropRows.size()+" crops, "+patchRows.size()+" patches, "+furniture.size()+" furniture recipes, "+stations.size()+" workbenches, "+pins.size()+" assets");
 }
}
