#!/usr/bin/env python3
"""Reproduce the firemaking asset bindings using read-only 910 and 950 caches.

No old cache is needed at runtime: Native950Firemaking checks the generated hashes
against the selected950 cache. Item names below record the paired-cache inspection;
actual gameplay additionally uses ItemDefinitions.decodeStrict947.
"""
import hashlib
import json
from pathlib import Path
import sys
sys.dont_write_bytecode=True
import generate_950_npc_combat_animations as sequence

ROOT=Path(__file__).resolve().parents[1]
ITEMS={1511:'Logs',2862:'Achey tree logs',1521:'Oak logs',1519:'Willow logs',6333:'Teak logs',
       10810:'Arctic pine logs',1517:'Maple logs',6332:'Mahogany logs',12581:'Eucalyptus logs',
       1515:'Yew logs',1513:'Magic logs',40338:'Corrupted magic logs',13567:'Cursed magic logs',
       29556:'Elder logs',590:'Tinderbox',592:'Ashes'}
SEQUENCES=(16700,16703,16702)
FIRES=(70755,70756,70757,70758,70759,70760,70761,70762,70763,70764,70765,70766,70769)

def main():
    old=sequence.v.Packed(ROOT.parent/'Ataraxia-PS/data/cache')
    rows=[];lines=['# Generated by tools/verify_950_firemaking_assets.py.']
    for kind,index,shift,ids in [('sequence',20,7,SEQUENCES),('object',16,8,FIRES),('item',19,8,ITEMS)]:
        for id in ids:
            mask=(1<<shift)-1
            a=old.archive(index,id>>shift)[id&mask]
            b=sequence.v.cache.archive(index,id>>shift)[id&mask]
            row=dict(kind=kind,id=id,sha256=hashlib.sha256(b).hexdigest(),legacySha256=hashlib.sha256(a).hexdigest())
            if kind=='sequence':
                compatibility,definition,reason=sequence.compatibility(a,b)
                assert compatibility,(id,reason)
                row.update(compatibility=compatibility,durationCycles=definition['durationCycles'])
            elif kind=='object':
                assert a==b,id
                row['compatibility']='identical-definition'
            else:
                # These ordinary IDs retain their authored name, while modern menus/params changed.
                # The marker is opcode2 plus its exact NUL-terminated known name; Java's strict
                # decoder validates the entire definition at gameplay admission.
                name=ITEMS[id]; marker=b'\x02'+name.encode('ascii')+b'\x00'
                assert marker in a and marker in b,id
                row.update(name=name,compatibility='same-authored-item-name-current-definition-pin')
            rows.append(row);lines.append('%s.%d=%s'%(kind,id,row['sha256']))
    (ROOT/'Ataraxia950/resources/native950/firemaking-assets-950.properties').write_text('\n'.join(lines)+'\n',encoding='ascii')
    report=dict(assets=rows,excluded={'3239':'Old Evil bark is modern Bark; not admitted as the old high-XP log.','34528':'Protean log resource and XP rules are separate.'},
                limitation='Matching definitions/frame references establish authored roles but do not prove identical rendered models.')
    (ROOT/'protocol-analysis/firemaking-assets-950.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
    print('Verified %d firemaking assets.'%len(rows))

if __name__=='__main__':main()
