package com.rs.game.player.client;
import com.rs.game.WorldTile;import com.rs.game.item.Item;import com.rs.game.player.Player;import com.rs.game.player.Skills;import com.rs.game.player.actions.Cooking.Cookables;import io.netty.channel.embedded.EmbeddedChannel;import java.util.*;import org.junit.*;import static org.junit.Assert.*;
public class Native950ProductionFeedbackTest {
 private Player p;private EmbeddedChannel channel;
 @Before public void setup(){channel=new EmbeddedChannel();p=Player.createNative950("recipe-feedback",new WorldTile(3217,3258,0),channel);p.setActive(true);List<Native950ItemCatalog.Entry> types=new ArrayList<>();for(int id:new int[]{1511,52,53,314,946,4162,199,249,227})types.add(new Native950ItemCatalog.Entry(id,"Item "+id,id==52||id==53||id==314,new String[5]));Native950Skilling.attach(p,new Native950Containers(p,new Native950ItemCatalog(types)));}
 @After public void close(){p.getActionManager().forceStop();Native950Skilling.detach(p);channel.finishAndReleaseAll();}
 private void put(int slot,int id,int n){p.getInventory().items.set(slot,new Item(id,n));}
 private Native950Production.Recipe recipe(Item[] in,Item[] out,int... tools){return new Native950Production.Recipe("Test",Skills.CRAFTING,1,0,-1,1,in,out,tools);}
 @Test public void shortageAggregatesDuplicateIngredients(){put(0,52,20);Native950Production.Recipe r=recipe(new Item[]{new Item(52,15),new Item(52,15)},new Item[]{new Item(53,15)});assertEquals(0,r.maximumByMaterials(p));assertTrue(r.refusal(p).contains("10 more"));assertTrue(r.refusal(p).contains("30 required, 20"));assertEquals(20,p.getInventory().getAmountOf(52));}
 @Test public void makeAllCountsBatchesNotProducedUnitsAndDoesNotOverflow(){put(0,52,Integer.MAX_VALUE);put(1,314,60);Native950Production.Recipe r=recipe(new Item[]{new Item(52,15),new Item(314,15)},new Item[]{new Item(53,15)});assertEquals(4,r.maximumByMaterials(p));assertTrue(Arrays.toString(r.details(p)).contains("15 x item 53"));assertEquals(Integer.MAX_VALUE,p.getInventory().getAmountOf(52));}
 @Test public void fullInventoryReplacementDiffersFromExtraOutputFailure(){for(int i=0;i<28;i++)put(i,199,1);Native950Production.Recipe r=recipe(new Item[]{new Item(199,1)},new Item[]{new Item(249,1)});assertNull(r.refusal(p));r=recipe(new Item[]{new Item(199,1)},new Item[]{new Item(249,1),new Item(227,1)});assertTrue(r.refusal(p).contains("cannot hold the result"));assertEquals(28,p.getInventory().getAmountOf(199));}
 @Test public void toolAndProtectedItemRefusalsAreSpecificAndReadOnly(){put(0,1511,1);Native950Production.Recipe r=recipe(new Item[]{new Item(1511,1)},new Item[]{new Item(52,15)},4162);assertTrue(r.refusal(p).contains("4162"));put(1,4162,1);p.getInventory().getItem(0).setCharges(5);assertTrue(r.refusal(p).contains("charged or customised"));assertFalse(r.complete(p));assertEquals(1,p.getInventory().getAmountOf(1511));assertEquals(5,p.getInventory().getItem(0).getCharges());}
 @Test public void basicToolbeltCompletesRecipeWithoutBackpackTool(){put(0,1511,1);Native950Toolbelt.restore(p,new int[0]);Native950Production.Recipe r=recipe(new Item[]{new Item(1511,1)},new Item[]{new Item(52,15)},946);assertFalse(p.getInventory().containsItem(946,1));assertTrue(Native950Toolbelt.has(p,946));assertNull(r.refusal(p));assertTrue(r.complete(p));assertEquals(0,p.getInventory().getAmountOf(1511));assertEquals(15,p.getInventory().getAmountOf(52));assertTrue(Native950Toolbelt.has(p,946));assertTrue(Arrays.toString(r.details(p)).contains("backpack or tool belt"));}
 @Test public void movementIsSeparateFromMaterials(){put(0,1511,1);Native950Production.Recipe r=recipe(new Item[]{new Item(1511,1)},new Item[]{new Item(52,15)});p.setNextWorldTile(new WorldTile(3200,3200,0));assertFalse(Native950Production.Recipe.ready(p));assertTrue(r.refusal(p).contains("Finish moving"));assertEquals(1,r.maximumByMaterials(p));}
 @Test public void ordinaryBakingRequiresRangeWhileFishAndMeatUseEither(){assertTrue(Native950Cooking.needsRange(Cookables.RAW_APPLE_PIE));assertTrue(Native950Cooking.needsRange(Cookables.RAW_SUMMER_PIE));assertTrue(Native950Cooking.needsRange(Cookables.RAW_POTATO));assertFalse(Native950Cooking.needsRange(Cookables.RAW_MEAT));assertFalse(Native950Cooking.needsRange(null));}
}
