package com.rs.game.player.client;
import com.rs.game.WorldTile;import com.rs.game.item.Item;import com.rs.game.player.Player;import com.rs.game.player.Skills;
import io.netty.channel.embedded.EmbeddedChannel;import org.junit.*;import java.util.*;import static org.junit.Assert.*;
public class Native950SmithingActionTest {
 private Player p;private EmbeddedChannel channel;
 @Before public void setup(){channel=new EmbeddedChannel();p=Player.createNative950("smith-test",new WorldTile(3217,3258,0),channel);p.setActive(true);
  List<Native950ItemCatalog.Entry> rows=new ArrayList<>();for(int id:new int[]{2347,2349,1205,39})rows.add(new Native950ItemCatalog.Entry(id,"Item "+id,id==39,new String[5]));
  Native950Skilling.attach(p,new Native950Containers(p,new Native950ItemCatalog(rows)));}
 @After public void close(){p.getActionManager().forceStop();Native950Skilling.detach(p);channel.finishAndReleaseAll();}
 private void give(int id,int n){assertTrue(Native950Skilling.giveItem(p,id,n));}private int n(int id){return p.getInventory().items.getNumberOf(id);}
 private void run(int count){for(int i=0;i<count;i++)p.getActionManager().process();}
 private Native950Production.Recipe recipe(int bars,int output,int count,int level){return new Native950Production.Recipe("Smith: fixture",Skills.SMITHING,level,0,-1,2,new Item[]{new Item(2349,bars)},new Item[]{new Item(output,count)},2347);}
 private Native950SmithingAction action(int qty,int work){return new Native950SmithingAction(recipe(2,1205,1,1),qty,work,0,2,0);}
 @Test public void progressCannotGrantOrConsumeBeforeCompletionAndCancellation(){give(2347,1);give(2349,4);assertTrue(p.getActionManager().setAction(action(2,1000)));run(6);assertEquals(4,n(2349));assertEquals(0,n(1205));p.getActionManager().forceStop();run(100);assertEquals(4,n(2349));assertEquals(0,n(1205));}
 @Test public void selectedAmountStopsAndRetainsHammer(){give(2347,1);give(2349,6);assertTrue(p.getActionManager().setAction(action(2,56)));run(30);assertEquals(2,n(1205));assertEquals(2,n(2349));assertEquals(1,n(2347));assertFalse(p.getActionManager().hasSkillWorking());}
 @Test public void batchOutputUsesSingleBarAndExactCacheStyleQuantity(){give(2347,1);give(2349,1);assertTrue(p.getActionManager().setAction(new Native950SmithingAction(recipe(1,39,75,1),1,56,0,1,0)));run(10);assertEquals(75,n(39));assertEquals(0,n(2349));assertEquals(1,n(2347));}
 @Test public void fullInventoryExchangesFreedMaterialSlotsAtomically(){give(2347,1);give(2349,27);assertEquals(0,p.getInventory().getFreeSlots());assertTrue(p.getActionManager().setAction(action(1,56)));run(10);assertEquals(25,n(2349));assertEquals(1,n(1205));assertEquals(1,n(2347));}
 @Test public void toolbeltHammerStartsWithoutBackpackHammerAndSurvivesBackpackRemoval(){give(2349,4);assertTrue(Native950Toolbelt.has(p,2347));assertTrue(p.getActionManager().setAction(action(1,56)));run(10);assertEquals(1,n(1205));give(2347,1);assertTrue(p.getActionManager().setAction(action(1,1000)));run(5);p.getInventory().items.set(p.getInventory().items.lookupSlot(2347),null);run(400);assertEquals(0,n(2349));assertEquals(2,n(1205));assertEquals(0,n(2347));assertTrue(Native950Toolbelt.has(p,2347));}
 @Test public void toolbeltDoesNotBypassControllerVetoDuringProgress()throws Exception{give(2349,2);assertTrue(p.getActionManager().setAction(action(1,1000)));run(5);com.rs.game.player.controllers.Controller deny=new com.rs.game.player.controllers.Controller(){public void start(){}public boolean canAddInventoryItem(int id,int amount){return false;}};java.lang.reflect.Field f=com.rs.game.player.ControlerManager.class.getDeclaredField("controler");f.setAccessible(true);f.set(p.getControlerManager(),deny);f=com.rs.game.player.ControlerManager.class.getDeclaredField("inited");f.setAccessible(true);f.setBoolean(p.getControlerManager(),true);run(400);assertEquals(2,n(2349));assertEquals(0,n(1205));assertFalse(p.getActionManager().hasSkillWorking());}
 @Test public void missingMaterialAndInsufficientLevelRefuse(){give(2347,1);give(2349,1);assertFalse(p.getActionManager().setAction(action(1,56)));give(2349,1);assertFalse(p.getActionManager().setAction(new Native950SmithingAction(recipe(2,1205,1,50),1,56,50,2,0)));assertEquals(2,n(2349));}
 @Test public void stationInvalidationMidProgressStopsWithoutExchange(){give(2347,1);give(2349,2);final boolean[] current={true};Native950SmithingAction a=new Native950SmithingAction(recipe(2,1205,1,1),1,1000,0,2,0){protected boolean environment(Player ignored){return current[0];}};assertTrue(p.getActionManager().setAction(a));run(4);current[0]=false;run(100);assertEquals(2,n(2349));assertEquals(0,n(1205));}
 @Test public void stoppedActionQueuesGaugeRemovalAndPercentIsBounded(){assertEquals(255,Native950SmithingGauge.heat(101).getPercentage());assertEquals(0,Native950SmithingGauge.progress(-1).getPercentage());give(2347,1);give(2349,2);assertTrue(p.getActionManager().setAction(action(1,1000)));p.getActionManager().forceStop();assertEquals(2,p.getNextHitBars().size());for(com.rs.game.hitbar.HitBar b:p.getNextHitBars())assertTrue(((Native950SmithingGauge)b).isRemoval());}
}
