package modern947;

import com.rs.network.modern.Native950GameTransport;
import com.rs.network.modern.Native950Isaac;
import com.rs.network.protocol.modern950.Native950Packets;
import com.rs.network.protocol.modern950.Native950Protocol.ServerPacket;
import io.netty.buffer.ByteBuf;
import io.netty.channel.embedded.EmbeddedChannel;
import java.io.ByteArrayOutputStream;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Literal fixtures for the native 950-1 stat and scalar HUD packets.
 *
 * The three scalar packets keep their 947 bodies and change only their opcode. UPDATE_STAT does
 * not: 950 reverses it outright, so the expected bytes here are recomputed from the port plan's
 * field list rather than transcribed from verified/UPDATE_STAT.md, whose byte examples describe
 * 947. Nothing here is generated by the writers under test.
 */
public final class Native950StatWireTest {

    // --- UPDATE_STAT, opcode 92 (947: 66), size 6 ---------------------------------------------

    @Test public void updateStatUsesTheNativeExperienceLevelSkillOrderInWholePoints() {
        // 950 (parser 0x140141290) reverses 947's order: b0 = -skill, b1 = -level, then WHOLE
        // experience big-endian at b2..b5. Both leading bytes changed transform as well as
        // position - 947 wrote (128 - level) and (skill + 128), 950 negates each - so a 947 body
        // is not a permutation of a 950 one and the same three rows re-encode as:
        //   00 9d 00 c6 e3 bf ->  13,034,431 xp, level  99, skill  0
        //   fd f6 00 00 04 82 ->       1,154 xp, level  10, skill  3
        //   e6 88 06 32 ea 00 -> 104,000,000 xp, level 120, skill 26
        // The experience units are unchanged: whole points, not tenths (STAT_DEFINITIONS.md 3b.1
        // corrects UPDATE_STAT.md's "tenths" reading, and the cache agrees).
        Native950Packets.Packet packet = Native950Packets.updateStat(0, 99, 13034431);
        assertEquals(ServerPacket.UPDATE_STAT, packet.type());
        assertArrayEquals(hex("5c 009d00c6e3bf"), packet.frame(() -> 0));
        assertArrayEquals(hex("fdf600000482"), Native950Packets.updateStat(3, 10, 1154).payload());
        assertArrayEquals(hex("e6880632ea00"), Native950Packets.updateStat(26, 120, 104000000).payload());
    }

    @Test public void updateStatCoversBothTransformedByteBoundariesAndTheClientClamp() {
        // 950 decodes both leading bytes as a negation: skill = -b0 & 255, level = -b1 & 255.
        assertArrayEquals(hex("000000000000"), Native950Packets.updateStat(0, 0, 0).payload());
        assertArrayEquals(hex("010000000000"), Native950Packets.updateStat(255, 0, 0).payload());
        assertArrayEquals(hex("000100000000"), Native950Packets.updateStat(0, 255, 0).payload());
        assertArrayEquals(hex("008100000000"), Native950Packets.updateStat(0, 127, 0).payload());
        // 200,000,000 whole points is 0x0BEBC200, the flag-zero clamp the client's experience
        // setter 0x140369C10 applies to the live stat table at [[owner+0x198E0]+0x7618].
        assertArrayEquals(hex("00000bebc200"), Native950Packets.updateStat(0, 0, 200000000).payload());
        assertArrayEquals(hex("000000000001"), Native950Packets.updateStat(0, 0, 1).payload());
    }

    @Test public void updateStatRejectsIndicesLevelsAndExperienceTheWireCannotCarry() {
        rejects(() -> Native950Packets.updateStat(-1, 1, 0));
        rejects(() -> Native950Packets.updateStat(256, 1, 0));
        rejects(() -> Native950Packets.updateStat(0, -1, 0));
        rejects(() -> Native950Packets.updateStat(0, 256, 0));
        rejects(() -> Native950Packets.updateStat(0, 1, -1));
        rejects(() -> Native950Packets.updateStat(0, 1, 200000001));
        rejects(() -> Native950Packets.updateStat(0, 1, Integer.MAX_VALUE));
    }

    // --- UPDATE_RUNENERGY, opcode 21 (947: 116), size 1; body unchanged -----------------------

    @Test public void runEnergyIsOneUntransformedPercentageByte() {
        // UPDATE_RUNENERGY.md: 64 -> 100, 32 -> 50, 00 -> 0.
        Native950Packets.Packet packet = Native950Packets.runEnergy(100);
        assertEquals(ServerPacket.UPDATE_RUNENERGY, packet.type());
        assertArrayEquals(hex("15 64"), packet.frame(() -> 0));
        assertArrayEquals(hex("32"), Native950Packets.runEnergy(50).payload());
        assertArrayEquals(hex("00"), Native950Packets.runEnergy(0).payload());
        // The client range-checks nothing; the writer holds the 0..100 contract of cs2 op 731.
        rejects(() -> Native950Packets.runEnergy(-1));
        rejects(() -> Native950Packets.runEnergy(101));
    }

    // --- UPDATE_RUNWEIGHT, opcode 7 (947: 108), size 2; body unchanged ------------------------

    @Test public void runWeightIsABigEndianSignedShortInKilograms() {
        // UPDATE_RUNWEIGHT.md: 00 1E -> 30 kg, 00 00 -> 0 kg, FF F6 -> -10 kg.
        Native950Packets.Packet packet = Native950Packets.runWeight(30);
        assertEquals(ServerPacket.UPDATE_RUNWEIGHT, packet.type());
        assertArrayEquals(hex("07 001e"), packet.frame(() -> 0));
        assertArrayEquals(hex("0000"), Native950Packets.runWeight(0).payload());
        assertArrayEquals(hex("fff6"), Native950Packets.runWeight(-10).payload());
        assertArrayEquals(hex("7fff"), Native950Packets.runWeight(32767).payload());
        assertArrayEquals(hex("8000"), Native950Packets.runWeight(-32768).payload());
        rejects(() -> Native950Packets.runWeight(32768));
        rejects(() -> Native950Packets.runWeight(-32769));
    }

    // --- UPDATE_REBOOT_TIMER, opcode 31 (947: 52), size 2; body unchanged ---------------------

    @Test public void rebootTimerIsABigEndianUnsignedShortOfServerTicks() {
        // UPDATE_REBOOT_TIMER.md: 00 64 -> 100 ticks. The name is a meaning-derived convention.
        Native950Packets.Packet packet = Native950Packets.rebootTimer(100);
        assertEquals(ServerPacket.UPDATE_REBOOT_TIMER, packet.type());
        assertArrayEquals(hex("1f 0064"), packet.frame(() -> 0));
        assertArrayEquals(hex("0000"), Native950Packets.rebootTimer(0).payload());
        assertArrayEquals(hex("ffff"), Native950Packets.rebootTimer(65535).payload());
        rejects(() -> Native950Packets.rebootTimer(-1));
        rejects(() -> Native950Packets.rebootTimer(65536));
    }

    // --- Framing through the transport with the real outgoing ISAAC ---------------------------

    @Test public void statAndScalarWritersFrameThroughTheTransportWithTheRealOutgoingIsaac() {
        Native950GameTransport transport =
                Native950GameTransport.afterAuthentication(new int[] {1, 2, 3, 4}, Thread.currentThread());
        EmbeddedChannel channel = new EmbeddedChannel(transport);
        try {
            // afterAuthentication derives the outgoing stream from the login seeds plus 50.
            Native950Isaac reference = new Native950Isaac(new int[] {51, 52, 53, 54});
            Native950Packets.Packet[] written = {
                Native950Packets.updateStat(0, 99, 13034431),
                Native950Packets.runEnergy(100),
                Native950Packets.runWeight(-10),
                Native950Packets.rebootTimer(100)
            };
            byte[] first = null;
            for (int i = 0; i < written.length; i++) {
                channel.writeOutbound(written[i]);
                byte[] expected = written[i].frame(reference);
                byte[] actual = readOutput(channel);
                assertArrayEquals("framed packet " + i, expected, actual);
                if (i == 0) first = actual;
            }
            // First outgoing ISAAC word for login seeds 1,2,3,4 is 0x21fc9d18 (pinned by
            // Native950TransportTest), so opcode 92 leaves the wire as (92 + 0x18) = 0x74.
            assertArrayEquals(hex("74 009d00c6e3bf"), first);
            assertNull(transport.terminalFailure());
        } finally {
            channel.finishAndReleaseAll();
        }
    }

    @Test public void rejectedWritersNeverReachTheChannelOrConsumeTheOutgoingCipher() {
        Native950GameTransport transport =
                Native950GameTransport.afterAuthentication(new int[] {1, 2, 3, 4}, Thread.currentThread());
        EmbeddedChannel channel = new EmbeddedChannel(transport);
        try {
            rejects(() -> Native950Packets.updateStat(0, 1, 200000001));
            channel.writeOutbound(Native950Packets.updateStat(0, 99, 13034431));
            assertArrayEquals(hex("74 009d00c6e3bf"), readOutput(channel));
        } finally {
            channel.finishAndReleaseAll();
        }
    }

    private static byte[] readOutput(EmbeddedChannel channel) {
        ByteBuf output = channel.readOutbound();
        assertNotNull(output);
        try {
            byte[] bytes = new byte[output.readableBytes()];
            output.readBytes(bytes);
            return bytes;
        } finally {
            output.release();
        }
    }

    private static void rejects(Runnable action) {
        try { action.run(); fail("Invalid packet accepted"); }
        catch (IllegalArgumentException expected) { }
    }

    private static byte[] hex(String value) {
        String compact = value.replace(" ", "");
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        for (int i = 0; i < compact.length(); i += 2)
            bytes.write(Integer.parseInt(compact.substring(i, i + 2), 16));
        return bytes.toByteArray();
    }
}
