package com.rs.game.player.client;
import com.rs.game.WorldTile;import com.rs.game.item.Item;import com.rs.game.player.Player;import com.rs.game.player.Skills;import io.netty.channel.embedded.EmbeddedChannel;import java.util.*;import org.junit.*;import static org.junit.Assert.*;
public class Native950ProductionAlternativesTest {
 private Player p;private EmbeddedChannel channel;
 @Before public void setup(){channel=new EmbeddedChannel();p=Player.createNative950("recipe-alternatives",new WorldTile(3217,3258,0),channel);p.setActive(true);List<Native950ItemCatalog.Entry> types=new ArrayList<>();for(int id:new int[]{52,53,314,1511})types.add(new Native950ItemCatalog.Entry(id,"Item "+id,id!=1511,new String[5]));Native950Skilling.attach(p,new Native950Containers(p,new Native950ItemCatalog(types)));}
 @After public void close(){p.getActionManager().forceStop();Native950Skilling.detach(p);channel.finishAndReleaseAll();}
 private void put(int slot,int id,int n){p.getInventory().items.set(slot,new Item(id,n));}
 private Native950Production.Recipe base(){return new Native950Production.Recipe("Alternatives",Skills.CRAFTING,1,0,-1,1,new Item[]{new Item(52,2)},new Item[]{new Item(53,1)});}
 @Test public void switchesMaterialFamiliesOnlyBetweenCompleteBatches(){put(0,52,2);put(1,314,4);Native950Production.Recipe r=base().withAlternatives(52,314);assertEquals(3,r.maximumByMaterials(p));assertTrue(r.complete(p));assertEquals(0,p.getInventory().items.getNumberOf(52));assertEquals(4,p.getInventory().items.getNumberOf(314));assertTrue(r.complete(p));assertTrue(r.complete(p));assertEquals(3,p.getInventory().items.getNumberOf(53));assertFalse(r.complete(p));}
 @Test public void cannotCombineIncompleteMaterialKindsToMintAProduct(){put(0,52,1);put(1,314,1);Native950Production.Recipe r=base().withAlternatives(52,314);assertEquals(0,r.maximumByMaterials(p));assertFalse(r.complete(p));assertEquals(0,p.getInventory().items.getNumberOf(53));assertEquals(1,p.getInventory().items.getNumberOf(52));assertEquals(1,p.getInventory().items.getNumberOf(314));}
 @Test public void alternativeSnapshotsAndPreviewDoNotMutateOriginalRecipe(){int[] choices={314};Native950Production.Recipe original=base(),r=original.withAlternatives(52,choices);choices[0]=1511;put(0,314,2);assertFalse(original.usesInput(314));assertTrue(r.usesInput(314));assertFalse(r.usesInput(1511));assertEquals(0,original.maximumByMaterials(p));assertEquals(1,r.maximumByMaterials(p));Item[] selected=r.consumed(p);selected[0].setAmount(20);assertEquals(2,r.consumed(p)[0].getAmount());assertTrue(Arrays.toString(r.details(p)).contains("Interchangeable"));}
 @Test public void protectsChargedAlternativeInstances(){put(0,314,2);p.getInventory().getItem(0).setCharges(5);Native950Production.Recipe r=base().withAlternatives(52,314);assertTrue(r.refusal(p).contains("charged or customised"));assertFalse(r.complete(p));assertEquals(2,p.getInventory().items.getNumberOf(314));assertEquals(5,p.getInventory().getItem(0).getCharges());}
 @Test(expected=IllegalArgumentException.class) public void rejectsOverlapWithOtherConsumedMaterials(){new Native950Production.Recipe("Overlapping",Skills.CRAFTING,1,0,-1,1,new Item[]{new Item(52,2),new Item(314,1)},new Item[]{new Item(53,1)}).withAlternatives(52,314);}
 @Test public void rechecksSpaceForAlternativeStackThatRemainsAfterConsumption(){put(0,314,4);for(int i=1;i<28;i++)put(i,1511,1);Native950Production.Recipe r=base().withAlternatives(52,314);assertEquals(2,r.maximumByMaterials(p));assertTrue(r.refusal(p).contains("cannot hold the result"));assertFalse(r.complete(p));assertEquals(4,p.getInventory().items.getNumberOf(314));}
}
